# Generated by Django 5.1.1 on 2024-12-10 19:30

import django.db.models.deletion
import invoice.fileUtils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vendors', '0002_vendor_created_at_vendor_updated_at_historicalvendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='historicalvendor',
            name='files',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='files',
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_vendors', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=invoice.fileUtils.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('document_type', models.CharField(default='vendor', max_length=50)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_files', to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
