# Generated by Django 5.1.1 on 2024-12-12 18:33

import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_historicalvendor_status_vendor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='file',
            name='number',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='file',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='vendors/'),
        ),
    ]
