# Generated by Django 5.1.1 on 2024-12-12 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_remove_file_created_at_remove_file_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_files', to='vendors.vendor'),
        ),
    ]
