# Generated by Django 5.1.1 on 2024-12-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_file_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
