# Generated by Django 5.1.1 on 2024-12-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_historicalvendor_created_by_vendor_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendor',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
