# Generated by Django 5.1.1 on 2024-12-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('invoice', '0002_remove_emailfile_comment_remove_invoicefile_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_invoices', to='core.branch'),
        ),
    ]
