# Generated by Django 5.1.1 on 2024-12-26 14:41

import invoice.fileUtils
import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_historicalinvoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=invoice.fileUtils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='emailfile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=invoice.fileUtils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='invoicefile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=invoice.fileUtils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='pofile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=invoice.fileUtils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='quotefile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=invoice.fileUtils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='receivedfile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=invoice.fileUtils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='requisitionfile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=invoice.fileUtils.get_upload_path),
        ),
    ]
