# Generated by Django 5.1.1 on 2024-12-27 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_archivefile_created_by_emailfile_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='send_to_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='send_to_vendor_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='send_to_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='send_to_vendor_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
