# Generated by Django 5.1.1 on 2025-01-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('invoice', '0012_remove_contract_file_remove_contract_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_contracts', to='core.branch'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_invoices', to='invoice.contract'),
        ),
    ]
