# Generated by Django 5.1.1 on 2025-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_contract_branch_historicalcontract_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
