# Generated by Django 5.1.1 on 2025-01-03 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_contract_notes_historicalcontract_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
