# Generated by Django 5.1.1 on 2025-01-17 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_contract_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quote', 'Quote'), ('requisition', 'Requisition'), ('po', 'PO'), ('pending_po', 'Pending PO'), ('sent_to_vendor', 'Sent to Vendor'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quote', 'Quote'), ('requisition', 'Requisition'), ('po', 'PO'), ('pending_po', 'Pending PO'), ('sent_to_vendor', 'Sent to Vendor'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quote', 'Quote'), ('requisition', 'Requisition'), ('po_received', 'Received'), ('sent_to_ap', 'Sent to AP'), ('completed', 'Completed'), ('contract_invoice', 'Contract Invoice'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quote', 'Quote'), ('requisition', 'Requisition'), ('po_received', 'Received'), ('sent_to_ap', 'Sent to AP'), ('completed', 'Completed'), ('contract_invoice', 'Contract Invoice'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], default='pending', max_length=20),
        ),
    ]
